### ISSUE TITLE
Milestone 1 features

### ISSUE THREAD

**Issue by bennett1412** [bennett1412/do-note#1]
- [x] cloud sync
- [x] basic crud ops
- [x] insert image from clipboard
- [x] change note color
