### ISSUE TITLE
Milestone 2 features

### ISSUE THREAD

**Issue by bennett1412** [bennett1412/do-note#2]
- [x] convert to pwa
- [x] copy to clipboard
- [ ] voice to text 
- [ ] offline and anon mode
- [ ] collaborative editing
